import type { Metadata } from "next";
import "../../styles/globals.css";
import Header from "@/components/header/header";
import Navbar from "@/components/navbar/navbar";
import ClientLayout from "@/components/client-layout";

// 메타데이터 설정
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <ClientLayout>
    <div className="min-h-screen flex flex-col items-center relative">
      <div className="w-full h-16 bg-loginLightGreen z-20 fixed top-0 left-0">
        <Header />
      </div>

      {/* Main Content */}
      <main className="w-full mx-auto relative z-10 overflow-x-auto">
        {children}
      </main>

      <div className="w-full bg-loginLightGreen fixed bottom-0 left-0 z-20">
        <Navbar />
      </div>
    </div>
    </ClientLayout>
  );
};

export default RootLayout;
